name=Alfredo-NoU3
version=1.13
author=Alfredo Systems
maintainer=Jacob Williams (jrw4561@gmail.com)
sentence=Library for the Alfredo NoU3 robot control board.
paragraph=Supports driving motors and servos. Has helper methods for different drivetrain types.
category=Device Control
url=https://github.com/AlfredoSystems/Alfredo-NoU3
architectures=esp32
